apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cheese.crd.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: "cheese"
spec:
  group: crd.io
  version: v1
  scope: Namespaced
  names:
    plural: cheeses
    kind: cheese

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wine.crd.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: "wine"
spec:
  group: crd.io
  version: v1
  scope: Namespaced
  names:
    plural: wines
    kind: wine

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tartiflette.crd.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: "tartiflette"
spec:
  group: crd.io
  version: v1
  scope: Namespaced
  names:
    plural: tartiflettes
    kind: tartiflette
