apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: really-long
    build: "1"
    foo: bar
    fruit: apple
    jenkins.io/pipelineType: build
    owner: abayer
    repository: js-test-repo
    way-too-long-a-label-seriously-this-just-goes-on-for-so-many-ch: this-hasinvalidcharacters
  name: abayer-js-test-repo-really-long-m97mw-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-js-test-repo-really-long-m97mw-1
  podTemplate:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              foo: bar
              fruit: apple
              way-too-long-a-label-seriously-this-just-goes-on-for-so-many-ch: this-hasinvalidcharacters
          topologyKey: kubernetes.io/hostname
    schedulerName: ""
  resources:
  - name: abayer-js-test-repo-really-long-m97mw
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-js-test-repo-really-long-m97mw
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
