apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: abayer
    repository: jx-demo-qs
  name: abayer-jx-demo-qs-master-b5j7r-1
  namespace: jx
spec:
  params:
  - default: 0.0.1
    description: the version number for this pipeline which is used as a tag on docker
      images and helm charts
    name: version
    type: string
  resources:
  - name: abayer-jx-demo-qs-master-b5j7r
    type: git
  tasks:
  - name: from-build-pack
    params:
    - name: version
      value: $(params.version)
    resources:
      inputs:
      - name: workspace
        resource: abayer-jx-demo-qs-master-b5j7r
    taskRef:
      name: abayer-jx-demo-qs-master-b5j7r-from-build-pack-1
