apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: abayer
    repository: jx-demo-qs
  name: abayer-jx-demo-qs-master-mz4c7-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-jx-demo-qs-master-mz4c7-1
  podTemplate:
    schedulerName: ""
  resources:
  - name: abayer-jx-demo-qs-master-mz4c7
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-jx-demo-qs-master-mz4c7
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
